### ISSUE TITLE
Trying to understand where I place config files

### ISSUE THREAD

**Issue by carnellj** [macchiato-framework/examples#6]
Hi guys,

I am familiar with clojure but not clojurescript.  Love what I am seeing in Macchiato.  I am just trying to figure out where specifically I am suppose to put a config.edn so it will be picked up and read when my service starts.  Also, I am just trying to figure out how I am supposed to be accessing the service.  So for example, 

if I have a configure.edn that contains the following entry: {:twilio-auth-sid "abc"}  would I access the property via  {:twilio-auth-side @env}.

Any help would be greatly appreciated.

     Thanks,
        John

**Comment by yogthos** [comment]
The app will look for the `config.edn` file relative to where you start it, or at the location pointed to by the `CONF` environment variable. And you'd access the entries using parens as a function call, e.g: `(:twilio-auth-side @env)`.
